const router = require("express").Router();
const langRouter = require("./langs.routes")
const categoRouter = require("./category.routes")
const newsRouter = require("./news.routes")
const usersRouter = require("./users.routes")
const newslangRouter = require("./newslang.routes")
const mediaRouter = require("./media.routes")
const commentRouter = require("./comment.routes")
const reportsRouter = require("./reports.routes")
const viewsRouter = require("./views.routes")
const likeRouter = require("./likes.routes")
const newsTagRouter = require("./newstag.routes")
const tagRouter = require("./tags.routes")
const authorRouter = require("./author.routes")
const notiRouter = require("./notifaction.routes")
const otpRouter = require("./otp.routes")

router.use("/lang",langRouter)
router.use("/catego",categoRouter)
router.use("/news",newsRouter)
router.use("/users",usersRouter)
router.use("/newslang",newslangRouter)
router.use("/media",mediaRouter)
router.use("/comment",commentRouter)
router.use("/report",reportsRouter)
router.use("/view",viewsRouter)
router.use("/like",likeRouter)
router.use("/news-tag",newsTagRouter)
router.use("/tag",tagRouter)
router.use("/author",authorRouter)
router.use("/notifaction",notiRouter)
router.use("/otp",otpRouter)


module.exports = router